# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: å¼ ä¾ƒ â€” æ—…è¡Œä½œè€… & ç¯çƒè‡ªé©¾å®¢
  params:
    description: Site description in Chinese...
  menu:
    main:
      - name: ä¸»é¡µ
        url: '#about'
        weight: 10
      - name: æ—…è¡Œåšå®¢
        url: 'https://drive2world.com/zh/'
        weight: 20
      - name: é¡¹ç›®
        url: '#projects'
        weight: 30
      - name: è®²åº§
        url: '#talks'
        weight: 40
      - name: ä½œå“
        url: '#featured'
        weight: 50
      - name: è”ç³»æˆ‘
        url: '#contact'
        weight: 60
      - name: ğŸ‡ºğŸ‡¸ English
        url: '/en/'
        weight: 70
